name: stray
description: "周浦小学失物认领程序, 由五(4)班张时嘉开发"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  http: ^1.0.0
  ez_circle_avatar: ^0.0.3
  tencentcloud_cos_sdk_plugin: ^1.2.6
  image_picker: ^1.2.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/stray-icon.png"
